.github/workflows: use service account json creds
Firebase Hosting API doesn't support workload identity.

```
ERROR: create site version: googleapi: Error 401: Request had invalid
authentication credentials. Expected OAuth 2 access token, login cookie or
other valid authentication credential.
```